# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d607db039e1230a8060b650f87eda06c1366bbf21550a54ffccb3c5bf586240cad111ec9bc2092bf501a6493db5771717d94252146f927b95003200afa68be

test:
  secret_key_base: ebd5ee91641650a0fc193d63177c2219be3cca925a0d2678095708407fd130a47e8f67614b2f9bf88189c5c2d2c833ea8150d3ad2e443346bf789bcfb8a3f10d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
